#!/usr/bin/env node
"use strict";
const fs = require("fs");
const path = require("path");

const target = process.argv[2] || ".";
const ROOT = path.resolve(__dirname, target);
const { ROOK_REGISTER, evaluateCaGate, deriveHandle } = require(path.join(ROOT, "js", "register.js"));

console.log(`Checking: ${ROOT}\n`);

let failures = 0;
function check(name, fn) {
  try {
    const ok = fn();
    if (ok === false) throw new Error("check returned false");
    console.log(`  PASS  ${name}`);
  } catch (err) {
    console.log(`  FAIL  ${name} — ${err.message}`);
    failures++;
  }
}

console.log("Register pattern");
check("every register record has a valid status", () => {
  const validStatuses = new Set(["stated", "absent", "unconfirmed"]);
  const records = [ROOK_REGISTER.chain, ROOK_REGISTER.contractAddress, ...ROOK_REGISTER.socials];
  return records.every((r) => validStatuses.has(r.status));
});
check("stated social records carry a verification note", () => {
  return ROOK_REGISTER.socials
    .filter((s) => s.status === "stated")
    .every((s) => typeof s.verification === "string" && s.verification.length > 0);
});

console.log("\nLink rule");
check("deriveHandle produces a handle from a stored URL, not a typed literal", () => {
  return deriveHandle("https://x.com/Rook_Cash") === "@Rook_Cash";
});
check("no unstated social record carries a URL", () => {
  return ROOK_REGISTER.socials.filter((s) => s.status !== "stated").every((s) => !s.url);
});

console.log("\nGate warning — CA gate must be provably failable");
check("gate fails on a throwaway 0x-shaped address while CA is absent", () => {
  const outcome = evaluateCaGate(ROOK_REGISTER.contractAddress, "0x1234567890abcdef1234567890abcdef12345678");
  if (ROOK_REGISTER.contractAddress.status === "stated") return true; // gate re-tested below for stated case
  return outcome === "no-address-stated";
});
check("gate does not blanket-reject non-hex or malformed input either", () => {
  const outcome = evaluateCaGate(ROOK_REGISTER.contractAddress, "not-an-address-at-all");
  return typeof outcome === "string" && outcome.length > 0;
});
if (ROOK_REGISTER.contractAddress.status === "stated") {
  check("gate matches the exact stated address and rejects a near-miss", () => {
    const real = ROOK_REGISTER.contractAddress.value;
    const nearMiss = real.slice(0, -1) + (real.slice(-1) === "0" ? "1" : "0");
    return (
      evaluateCaGate(ROOK_REGISTER.contractAddress, real) === "match" &&
      evaluateCaGate(ROOK_REGISTER.contractAddress, nearMiss) === "no-match"
    );
  });
}

console.log("\nPalette rule — literals confined to tokens.css");
check("no bare hex color literals outside css/tokens.css", () => {
  const cssDir = path.join(ROOT, "css");
  const offenders = [];
  for (const file of fs.readdirSync(cssDir)) {
    if (file === "tokens.css") continue;
    const text = fs.readFileSync(path.join(cssDir, file), "utf8");
    const matches = text.match(/#[0-9a-fA-F]{3,8}\b/g);
    if (matches) offenders.push(`${file}: ${matches.join(", ")}`);
  }
  if (offenders.length) throw new Error(offenders.join(" | "));
  return true;
});
check("tokens.css palette entries carry a provenance comment", () => {
  const text = fs.readFileSync(path.join(ROOT, "css", "tokens.css"), "utf8");
  const sampledVars = ["--forest", "--rook-red", "--cream"];
  return sampledVars.every((v) => {
    const idx = text.indexOf(`\n  ${v}: #`);
    const before = text.slice(Math.max(0, idx - 250), idx);
    return /k-means|sampled at px/.test(before);
  });
});

console.log("\nRepo hygiene");
check("no CLAUDE.md at project root", () => !fs.existsSync(path.join(ROOT, "CLAUDE.md")));
check("no .claude directory at project root", () => !fs.existsSync(path.join(ROOT, ".claude")));
check("no AI-attribution strings in shipped site files", () => {
  const files = ["index.html", "css/styles.css", "css/tokens.css", "js/main.js", "js/register.js"];
  const pattern = /claude|anthropic|generated by ai|co-authored-by/i;
  const offenders = files.filter((f) => pattern.test(fs.readFileSync(path.join(ROOT, f), "utf8")));
  if (offenders.length) throw new Error(offenders.join(", "));
  return true;
});

console.log("\nAssets");
check("favicon.svg exists and is 32x32", () => {
  const svg = fs.readFileSync(path.join(ROOT, "favicon.svg"), "utf8");
  return /viewBox="0 0 32 32"/.test(svg);
});
check("index.html references favicon.svg", () => {
  const html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");
  return html.includes('href="favicon.svg"');
});

console.log(`\n${failures === 0 ? "All gates passed." : `${failures} gate(s) failed.`}`);
process.exit(failures === 0 ? 0 : 1);
